#!/bin/bash
# Build wrapper: runs buildroot inside a Debian container (host distro
# agnostic - rolling distros like Arch regularly break buildroot's host
# packages).
#
#   ./build.sh                   -> full build (6.18.y longterm)
#   EDGE=1 ./build.sh            -> mainline 7.0.y kernel (Armbian edge config)
#   RT=1 ./build.sh              -> PREEMPT_RT kernel
#   DBG=1 ./build.sh             -> debugobjects + SLUB poison kernel
#   HZ=1000 ./build.sh           -> kernel tick rate (100|250|300|1000, default 250)
#   W=1 ./build.sh               -> Nova W: AIC8800DC SDIO WiFi (driver+fw+DTS)
#   JOBS=40 ./build.sh           -> parallelism (default 24: GCC ICEs at full -j)
#   ./build.sh menuconfig | linux-menuconfig | uboot-menuconfig | shell | <targets>
#
# Flavor handling: flags are composed into a generated defconfig
# (buildroot/output/nova-flavor.defconfig) and .config is regenerated
# automatically whenever the flavor changes - no manual "rm .config" or
# "linux-dirclean" needed. buildroot does NOT honor BR2_* overrides on the
# make command line, so the generated defconfig is the supported way.
#
# buildroot itself is cloned into ./buildroot (gitignored); downloads are
# cached in ./buildroot/dl across builds.

set -e
cd "$(dirname "$0")"

BR_BRANCH=2025.02.x
IMAGE=luckfox-nova-br

JOBS="${JOBS:-24}"

# kernel flavor
BRD='$(BR2_EXTERNAL_LUCKFOX_NOVA_PATH)/board/luckfox/nova'
KVER="${KVER:-6.18.35}"
KPATCHES="$BRD/patches/linux"
KCONF="$BRD/linux.config"
if [ "${EDGE:-0}" = 1 ]; then
    KVER="${KVER_EDGE:-7.0.12}"
    KPATCHES="$BRD/patches/linux-edge"
    KCONF="$BRD/linux-edge.config"
    echo "[INFO] edge kernel build enabled ($KVER)"
fi

KCFG_FRAGS="$BRD/linux.fragment"
if [ "${RT:-0}" = 1 ]; then
    KCFG_FRAGS="$KCFG_FRAGS $BRD/linux-rt.fragment"
    echo "[INFO] PREEMPT_RT kernel build enabled"
fi
if [ "${DBG:-0}" = 1 ] || [ "${DEBUG:-0}" = 1 ]; then
    KCFG_FRAGS="$KCFG_FRAGS $BRD/linux-debug.fragment"
    echo "[INFO] debugobjects kernel build enabled"
fi
if [ -n "${HZ:-}" ]; then
    case "$HZ" in
        100|250|300|1000) ;;
        *) echo "[ERROR] HZ must be 100, 250, 300 or 1000"; exit 1 ;;
    esac
    # generated below once buildroot/output exists; the value is part of the
    # file name so the flavor stamp notices a change and recleans the kernel
    KCFG_FRAGS="$KCFG_FRAGS /work/buildroot/output/nova-hz-$HZ.fragment"
    echo "[INFO] HZ=$HZ kernel build enabled"
fi
if [ "${W:-0}" = 1 ]; then
    # Nova W: extra DTS patch dir (enables &sdio + wifi pwrseq), cfg80211,
    # and the aic8800dc driver package (added to the defconfig below).
    KPATCHES="$KPATCHES ${KPATCHES}-w"
    KCFG_FRAGS="$KCFG_FRAGS $BRD/linux-wifi.fragment"
    echo "[INFO] Nova W (AIC8800DC SDIO WiFi) build enabled"
fi

if [ ! -d buildroot ]; then
    echo "[INFO] cloning buildroot ($BR_BRANCH) ..."
    git clone --branch "$BR_BRANCH" https://gitlab.com/buildroot.org/buildroot.git buildroot
fi

# Cheap when cached; picks up Dockerfile changes automatically.
docker build -q -t "$IMAGE" docker/ >/dev/null

DOCKER_RUN=(docker run --rm -it \
    --user "$(id -u):$(id -g)" \
    -e HOME=/work \
    -v "$PWD:/work" \
    -w /work/buildroot \
    "$IMAGE")

if [ "${1:-}" = "shell" ]; then
    exec "${DOCKER_RUN[@]}" /bin/bash
fi

# ---- compose the flavor defconfig ---------------------------------------
# Later assignments win during defconfig processing, so the flavor lines
# simply override the base ones.
mkdir -p buildroot/output
if [ -n "${HZ:-}" ]; then
    {
        for hz in 100 250 300 1000; do
            if [ "$hz" = "$HZ" ]; then
                echo "CONFIG_HZ_$hz=y"
            else
                echo "# CONFIG_HZ_$hz is not set"
            fi
        done
        echo "CONFIG_HZ=$HZ"
    } > "buildroot/output/nova-hz-$HZ.fragment"
fi
FLAVOR=buildroot/output/nova-flavor.defconfig
{
    cat configs/luckfox_nova_defconfig
    echo ""
    echo "# ---- generated by build.sh (flavor) ----"
    echo "BR2_JLEVEL=$JOBS"
    echo "BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE=\"$KVER\""
    echo "BR2_LINUX_KERNEL_PATCH=\"$KPATCHES\""
    echo "BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE=\"$KCONF\""
    echo "BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES=\"$KCFG_FRAGS\""
    [ "${W:-0}" = 1 ] && echo "BR2_PACKAGE_AIC8800DC=y"
} > "$FLAVOR"

# ---- regenerate .config and clean the kernel when the flavor changes ----
STAMP=buildroot/output/.nova-flavor-applied
KSTAMP=buildroot/output/.nova-kernel-flavor
grep '^BR2_LINUX_KERNEL' "$FLAVOR" > "$FLAVOR.kernel"

# buildroot leaves a disabled package's already-installed files in target/,
# so a W=1 build followed by a plain build would still ship the AIC8800DC
# driver, firmware and S35 init script (the driver would load at boot). Scrub
# them on the W on->off transition (previous flavor had it, the new one does not).
if grep -q '^BR2_PACKAGE_AIC8800DC=y' "$STAMP" 2>/dev/null && \
   ! grep -q '^BR2_PACKAGE_AIC8800DC=y' "$FLAVOR"; then
    echo "[INFO] W disabled -> scrubbing stale AIC8800DC artifacts from target/"
    rm -rf buildroot/output/target/lib/firmware/aic8800_sdio \
           buildroot/output/target/lib64/firmware/aic8800_sdio \
           buildroot/output/target/lib/modules/*/updates/aic8800_bsp \
           buildroot/output/target/lib/modules/*/updates/aic8800_fdrv \
           buildroot/output/target/etc/init.d/S35aic8800dc \
           buildroot/output/target/etc/modprobe.d/aic8800dc.conf
    "${DOCKER_RUN[@]}" make BR2_EXTERNAL=/work aic8800dc-dirclean || true
fi

if [ ! -f buildroot/.config ] || ! cmp -s "$FLAVOR" "$STAMP"; then
    echo "[INFO] flavor changed -> regenerating .config"
    # clean the kernel only when its version/patches/config actually changed
    if ! cmp -s "$FLAVOR.kernel" "$KSTAMP" && \
       ls -d buildroot/output/build/linux-* >/dev/null 2>&1; then
        echo "[INFO] kernel flavor changed -> linux-dirclean"
        "${DOCKER_RUN[@]}" make BR2_EXTERNAL=/work linux-dirclean || true
        # out-of-tree kernel modules don't auto-rebuild when the kernel does,
        # so they keep a stale .ko (wrong vermagic) and buildroot won't redo
        # them. Dirclean them too so they rebuild against the new kernel.
        if ls -d buildroot/output/build/aic8800dc-* >/dev/null 2>&1; then
            echo "[INFO] kernel flavor changed -> aic8800dc-dirclean"
            "${DOCKER_RUN[@]}" make BR2_EXTERNAL=/work aic8800dc-dirclean || true
        fi
    fi
    "${DOCKER_RUN[@]}" make BR2_EXTERNAL=/work defconfig \
        BR2_DEFCONFIG=/work/buildroot/output/nova-flavor.defconfig
    cp "$FLAVOR" "$STAMP"
    cp "$FLAVOR.kernel" "$KSTAMP"
fi

exec "${DOCKER_RUN[@]}" make BR2_EXTERNAL=/work "$@"
