#!/bin/bash
# Build wrapper: runs buildroot inside a Debian container (host distro
# agnostic - rolling distros like Arch regularly break buildroot's host
# packages).
#
#   ./build.sh                   -> full build (6.18.y longterm)
#   EDGE=1 ./build.sh            -> mainline 7.0.y kernel (Armbian edge config)
#   RT=1 ./build.sh              -> PREEMPT_RT kernel
#   DBG=1 ./build.sh             -> debugobjects + SLUB poison kernel
#   JOBS=40 ./build.sh           -> parallelism (default 24: GCC ICEs at full -j)
#   ./build.sh menuconfig | linux-menuconfig | uboot-menuconfig | shell | <targets>
#
# Flavor handling: flags are composed into a generated defconfig
# (buildroot/output/nova-flavor.defconfig) and .config is regenerated
# automatically whenever the flavor changes - no manual "rm .config" or
# "linux-dirclean" needed. buildroot does NOT honor BR2_* overrides on the
# make command line, so the generated defconfig is the supported way.
#
# buildroot itself is cloned into ./buildroot (gitignored); downloads are
# cached in ./buildroot/dl across builds.

set -e
cd "$(dirname "$0")"

BR_BRANCH=2025.02.x
IMAGE=luckfox-nova-br

JOBS="${JOBS:-24}"

# kernel flavor
BRD='$(BR2_EXTERNAL_LUCKFOX_NOVA_PATH)/board/luckfox/nova'
KVER="${KVER:-6.18.35}"
KPATCHES="$BRD/patches/linux"
KCONF="$BRD/linux.config"
if [ "${EDGE:-0}" = 1 ]; then
    KVER="${KVER_EDGE:-7.0.12}"
    KPATCHES="$BRD/patches/linux-edge"
    KCONF="$BRD/linux-edge.config"
    echo "[INFO] edge kernel build enabled ($KVER)"
fi

KCFG_FRAGS="$BRD/linux.fragment"
if [ "${RT:-0}" = 1 ]; then
    KCFG_FRAGS="$KCFG_FRAGS $BRD/linux-rt.fragment"
    echo "[INFO] PREEMPT_RT kernel build enabled"
fi
if [ "${DBG:-0}" = 1 ] || [ "${DEBUG:-0}" = 1 ]; then
    KCFG_FRAGS="$KCFG_FRAGS $BRD/linux-debug.fragment"
    echo "[INFO] debugobjects kernel build enabled"
fi

if [ ! -d buildroot ]; then
    echo "[INFO] cloning buildroot ($BR_BRANCH) ..."
    git clone --branch "$BR_BRANCH" https://gitlab.com/buildroot.org/buildroot.git buildroot
fi

# Cheap when cached; picks up Dockerfile changes automatically.
docker build -q -t "$IMAGE" docker/ >/dev/null

DOCKER_RUN=(docker run --rm -it \
    --user "$(id -u):$(id -g)" \
    -e HOME=/work \
    -v "$PWD:/work" \
    -w /work/buildroot \
    "$IMAGE")

if [ "${1:-}" = "shell" ]; then
    exec "${DOCKER_RUN[@]}" /bin/bash
fi

# ---- compose the flavor defconfig ---------------------------------------
# Later assignments win during defconfig processing, so the flavor lines
# simply override the base ones.
mkdir -p buildroot/output
FLAVOR=buildroot/output/nova-flavor.defconfig
{
    cat configs/luckfox_nova_defconfig
    echo ""
    echo "# ---- generated by build.sh (flavor) ----"
    echo "BR2_JLEVEL=$JOBS"
    echo "BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE=\"$KVER\""
    echo "BR2_LINUX_KERNEL_PATCH=\"$KPATCHES\""
    echo "BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE=\"$KCONF\""
    echo "BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES=\"$KCFG_FRAGS\""
} > "$FLAVOR"

# ---- regenerate .config and clean the kernel when the flavor changes ----
STAMP=buildroot/output/.nova-flavor-applied
KSTAMP=buildroot/output/.nova-kernel-flavor
grep '^BR2_LINUX_KERNEL' "$FLAVOR" > "$FLAVOR.kernel"
if [ ! -f buildroot/.config ] || ! cmp -s "$FLAVOR" "$STAMP"; then
    echo "[INFO] flavor changed -> regenerating .config"
    # clean the kernel only when its version/patches/config actually changed
    if ! cmp -s "$FLAVOR.kernel" "$KSTAMP" && \
       ls -d buildroot/output/build/linux-* >/dev/null 2>&1; then
        echo "[INFO] kernel flavor changed -> linux-dirclean"
        "${DOCKER_RUN[@]}" make BR2_EXTERNAL=/work linux-dirclean || true
    fi
    "${DOCKER_RUN[@]}" make BR2_EXTERNAL=/work defconfig \
        BR2_DEFCONFIG=/work/buildroot/output/nova-flavor.defconfig
    cp "$FLAVOR" "$STAMP"
    cp "$FLAVOR.kernel" "$KSTAMP"
fi

exec "${DOCKER_RUN[@]}" make BR2_EXTERNAL=/work "$@"
