default luckfox-nova

label luckfox-nova
	kernel /boot/Image
	devicetree /boot/rk3308-luckfox-nova.dtb
	append console=ttyS4,1500000 earlycon=uart8250,mmio32,0xff0e0000 root=PARTUUID=8b3258a1-71e1-4f60-9f4a-6ab0c5a4e301 rootwait rw cma=16M
